sezna/nps

- package.json
You mean like this?
ref: https://github.com/kentcdodds/p-s/issues/1
> add additonal bin reference

- .all-contributorsrc
- README.md
- src/index.js
- src/index.test.js
**What**:
Show a more descriptive error message when the script was not found.
**Why**:
The error message was imho too cryptic.
**How**:
Simple string change.
Until now, the error message displayed was kind of short and uninformative. This PR makes the error
message more informative by displaying the name of the script that was not found.
> feat: Show a more descriptive error when the script was not found

- README.md
**What**: Add "In the wild" section with links to 3rd-party libs using `p-s` as functional part
**Why**: Some usages that may not be initially intended as `p-s` goal, but can give inspiration and ideas for other users
**How**: -
> docs(in-the-wild): Add "In the wild" section

- .all-contributorsrc
- README.md
- bin/p-s.js
**What**:
Rising the log level to error.
> Changing Unable to Find Config Log Level

- bin/p-s.js
**Why**:
P-S would terminate anyway because it couldn't find a script.
> P-S Exits Now If No Config File Could Be Found

- .all-contributorsrc
- README.md
**What**:
Added EventsSpeedTests to the "In the wild" section of the README.
**Why**:
`p-s` helped automated EventsSpeedTests without resorting to gulp, etc.  And requested by @kentcdodds :  https://twitter.com/kentcdodds/status/739203431634591744
**How**:
Updated the README.
> docs(in-the-wild): Add EventsSpeedTests to the "In the wild" section

- README.md
- src/bin/p-s.js
Update some docs as well.
This should be merged after #45 is merged.
> feat(help): add help command

- README.md
**What**: Added Smithers to the in the wild examples
**Why**: To show people that this tool is awesome
**How**: using a keyboard ;)
> add Smithers to the `in the wild` list

- README.md
> Readme: use correct highlighter for the yaml block

- README.md
**What**: docs(README): fix video description and time
**Why**: It is incorrect
**How**: An editor :)
> docs(README): fix video description and time

- .travis.yml
Just bringing things up to date with my generator :)
> chore(travis): update config

- README.md
Might be possible to have them combine efforts here.
**What**: Add readme link to [NABS](https://github.com/artlogic/nabs) other solution
**Why**: NABS (not another build system) is very similar to nps
**How**: typing. ;P
> Add link to NABS as another similar solution

- .all-contributorsrc
- README.md
Removed paragraph about nps alias that was no longer valid
#117
**What**:
**Why**:
**How**:
> docs(README): Remove out-dated README note

- .gitignore
- src/bin-utils/initialize/fixtures/_package-scripts.js
- src/bin-utils/initialize/fixtures/_package-scripts.yml
- src/bin-utils/initialize/fixtures/_package.json
- src/bin-utils/initialize/index.js
- src/bin-utils/initialize/index.test.js
**What**: I've added proper handling of pre and post scripts.
**Why**: To make nps scripts work same as how they work in npm.
**How**: Modified method responsible for structuring scripts before they are serialized to string. Also adjusted tests.
Could you look for expected yaml file? I am not familiar with this type of file and want to be sure I edited it correctly. Using quotes in this format of file is really confusing 😖 
https://github.com/kentcdodds/nps/issues/108
> feat(init): keep pre and post scripts as they work in npm

- README.md
**What**:
A badge to indicate the repository uses nps. Closes #157 
**Why**:
We love badges
**How**:
Making an issue, kentcdodds made a badge, and I crafted the PR
**Checklist**:
> docs(README): nps-friendly badge added to documentation (#157)

- package.json
- src/__tests__/index.js
- src/bin-utils/__tests__/index.js
- src/bin-utils/__tests__/parser.js
**What**: Bump dev dependencies and other minor style changes.
**Why**: Good to have the deps updated and it also fixes a peer dependency warning.
**How**: Updated the package.json, fixed eslint errors, removed a duplicate test
**Checklist**:
|Package             |Current |Latest |
|--------------------|--------|-------|
|eslint              |3.19.0  |4.5.0  |
|eslint-plugin-babel |4.1.1   |4.1.2  |
|sinon               |1.17.7  |3.2.1  |
Useful links:
- sinon [migrating to 2.0](http://sinonjs.org/releases/v3.2.1/migrating-to-2.0/).
- sinon [migrating to 3.0](http://sinonjs.org/releases/v3.2.1/migrating-to-3.0/).
- eslint [migrating to 4.0](https://eslint.org/docs/user-guide/migrating-to-4.0.0).
This also fixes the following warning:
```
warning "eslint-config-kentcdodds@12.4.2" has …
```
> chore(package): Bump dev deps

- README.md
**What**:
Removed codesponsor.io link from readme.md
**Why**:
codeSponsor doesn't exist anymore and the image is giving 404 and the page doesn't exist anymore
**How**:
Removed the link from readme.md
**Checklist**:
> removed codeSponsor

- README.md
> docs(README): move paywalled video to new resources section below

- .travis.yml
**What**:
Bump CI npm and node versions
**Why**:
Allows test against modern versions
**How**:
travis config
**Checklist**:
> run CI against modern node and npm versions

- src/bin-utils/parser.js
**What**:
Fix a typo error in error message
**Why**:
Error message has a typo
**How**:
The typo is corrected
**Checklist**:
> fix: fix a typo in error message
