sezna/nps

.all-contributorsrc, .gitignore, src/kebab-and-camel-casify.js, src/kebab-and-camel-casify.test.js
casify should also return original task name to avoid common user errors. For example, for task name
like e2e, it is not obvious to see that it converts to camelCase e2E and kebab-case e-2-e. This
avoids scripts must resolve to string error if user passes in the original task name over camelified
or kebabified task name
=> fix(casify): fix casify to also return original task name

.all-contributorsrc, README.md, src/bin-utils.js, src/bin-utils.test.js
Fix #19 
The prefix was incorrect for the nested tasks when displaying the help section. This PR will fix the issue.
The issue was cause because we only passed the current prefix when trying to get the nested script, therefore only the last 2 nested prefix were displayed instead of all prefixes.
=> Fix nested tasks display in help

src/bin/p-s.js
**What**:
When running as child process with arguments (like `--config smth`), `process.argv` is never empty, though commander has no args.
Also it would be logically more correct to check `program.args`, since later we use it as `program.args[0]`.
```sh
/Users/nkbt/nkbt/react-swap/node_modules/p-s/dist/bin-utils.js:90
scripts = program.args[0].split(',');
^
TypeError: Cannot read property 'split' of undefined
at getScriptsAndArgs (/Users/nkbt/nkbt/react-swap/node_modules/p-s/dist/bin-utils.js:90:30)
at loadAndRun (/Users/nkbt/nkbt/react-swap/node_modules/p-s/dist/bin/p-s.js:47:56)
at Object.<anonymous> (/Users/nkbt/nkbt/react-swap/node_modules/p-s/dist/bin/p-s.js:43:3)
```
**Why**
I want to proxy p-s from my component like
```js
require('child_process')
.spawn(ps, ['--config', …
```
=> Fix running as child process

src/bin-utils.js, src/bin-utils.test.js, src/bin/p-s.js
**What**:
Fixes an issue with parallel scripts
**Why**:
PR #29 broke the following case:
```
p-s -p lint,test
```
**How**:
This commit fixes it by getting the scripts from the args first and seeing if there are any scripts available to run. If not, then we show the help message.
CC: @giladgo, @abhishekisnot, @rowanoulton, @tleunen, @jisaacks, @nkbt 
Could one of you give this the green light and press the green button please?
=> fix(cli): re-enable parallel scripts

.npmrc, package.json
=> Use exact dependency versions and add npmrc with save-exact setting

README.md, package.json, src/index.js, src/index.test.js
**What**:
This will search for a local node_modules/.bin directory and attempt to add it to the PATH (in a cross-platform way using `manage-path`).
**Why**:
So people can use these just as they would normal npm scripts. The only case where the PATH doesn't actually contain the npm bin is when you run the `p-s` script directly (rather than using npm scripts). This is an edge case, but it's still handy
**How**:
Use `find-up` to find the `node_modules/.bin` and `mange-path` to add it to the PATH in a cross-platform way
Closes #27
=> feat(PATH): add npm bin to path

src/get-script-to-run.js, src/get-script-to-run.test.js
**What**:
This adds logic to check first for non-default scripts, then fallback on
default scripts if none are found that satisfies the input
**Why**:
Because #25
**How**:
Create a clone of the config object and remove all default scripts,
check the prefix with that, if none is found attempt again with the
original config object.
Closes #25
BREAKING CHANGE: You're unlikely to have this problem, but if you had a
script that matched the prefix `def` for example, the default script
would be run. Now, your specific script will be run instead.
=> fix(default): Now default scripts will be a fallback only

README.md, src/bin-utils/initialize/fixtures/_package-scripts.js, src/bin-utils/initialize/fixtures/_package.json, src/bin-utils/initialize/index.js, src/bin/p-s.js, src/index.js, src/index.test.js
**What**:
Adds support for the use case where running `p-s` without arguments will run `scripts.default`
**Why**:
Because often servers are configured to run `npm start` by default.
**How**:
- check for any arguments and default to `['default']` if no scripts are given.
- Update the `init` script to account for a `start` script
Closes #33
=> feat(cli): add support for root default script

README.md, package-scripts.js, package.json, src/bin-utils/autocomplete/index.js, src/bin-utils/autocomplete/index.test.js, src/bin-utils/index.js, src/bin/p-s.js
**What**: This adds a command called `completion` which installs the
autocomplete shell script. It also adds the logic to provide the
autocompletion.
**Why**: Because that's pretty swell!
**How**: Using omelette which is pretty awesome.
@tleunen, @SamVerschueren, and @jamischarles, do ya'll mind trying this out?
```
npm install --global p-s@beta
nps completion <path-to-your-bash-profile-file>
nps <tab>
```
`<path-to-your-bash-profile-file>` defaults to `~/.bash_profile`.
I'd appreciate a code review as well :)
=> feat(autocomplete): add `completion` script to install autocomplete

package.json, src/bin/p-s.test.js
Fixes #31 
**What**:
**Why**:
Make sure that expected behavior is not broken with different updates
This is WIP, so later will rewrite commit messages, fix code style, etc.
Some of used functions may be abstracted, though I think it is ok to keep them with tests, closer to context.
Would be great to have some more common usecases to test. Maybe another 2-3 to play with. Then anyone could be able to add more tests when new functionality is added.
Feel free to object any of decisions made, let me know what looks good, what is not so.
Cheers!
=> [wip] Add End-2-End tests for CLI

README.md, src/bin/nps.js
I think this will reinforce the use of the `nps` alias. But worry that it'll make things a bit more confusing because `p-s` is the name of the repo/package.
=> docs(README): update title to use `nps`

README.md, src/bin-utils/index.js, src/bin-utils/initialize/fixtures/_package-scripts.yml, src/bin-utils/initialize/index.js, src/bin-utils/initialize/index.test.js, src/bin/nps.js
**What**: #66 
**Why**: in order to allow those who prefer YAML to JS to use `nps` in their existing projects
**How**: by checking for the presence of the type modifier and, if present, leveraging [js-yaml](https://github.com/nodeca/js-yaml) to convert & dump the user's configuration
allow using the `package.json` of an existing project to generate a `package-scripts.yml` file in
order to make it easier to start using `nps`
closes #66
=> feat(cli): allow initializing a YAML config

package.json
`eslint-import-resolver-babel-module` was complaining
=> chore(devDeps): add missing peer dep of babel-plugin-module-resolver

README.md, cli-test/__snapshots__/cli.test.js.snap, other/EXAMPLES.md, package-scripts.js, package.json, src/bin-utils/index.js, src/bin-utils/index.test.js, src/bin/nps.js, src/index.js, src/index.test.js, yarn.lock
**What**: Removes `parallel`
**Why**: Reduces complexity of the tool and its implementation.
**How**: It's still a work in progres...
This will be a breaking change... Still evaluating.
=> remove parallel

package.json, src/index.js, src/index.test.js, yarn.lock
**What**: this removes the `bluebird` dependency
**Why**: we're dropping support for <= Node v4, so we can use native
Promises
**How**: remove all references to `bluebird`
BREAKING CHANGE: This package now depends on native promises.
=> fix(deps): remove bluebird

.babelrc, package.json, yarn.lock
BREAKING CHANGE: This drops support for Node v0.12.x
=> perf(babel): target node v4

README.md
**What**: Changes README to document that you need to pass `yml` instead of `yaml`
**Why**: `yaml` is not a valid option according to the CLI output of nps
**How**: N/A, documentation edit
`nps` only allows `yml` not `yaml`. Once I fixed this, I still couldn't get it to work (something about the path to the package.json being null), but you at least need to pass `yml` to even get to that point.
=> Update README regarding how to init with yml

README.md, other/EXAMPLES.md, package-scripts.js, package.json, yarn.lock
**What**: This adds `nps-utils` to the docs and `package-scripts.js`
**Why**: Because people miss the simplicity of `--parallel` among other things :)
**How**: mostly docs changes, but some of the changes are in `package-scripts.js`
You might like this @tleunen :) And you should probably know about this @elijahmanor
=> fix: add nps-utils to docs and package-scripts.js

cli-test/__snapshots__/cli.test.js.snap, cli-test/cli.test.js, package.json, src/bin-utils/initialize/index.js, src/bin-utils/initialize/index.test.js, src/get-script-to-run.js, src/get-script-to-run.test.js, src/index.js, yarn.lock
Added an additional information displaying which script is executed.
**What**: Added information which script is executed.
**Why**: Because of #126 
**How**: Just added an additional chalk call and changed string concatenation for template literal.
=> refactor(cli): display which script is executed

src/index.js, src/index.test.js
**What**:
Handle missing scripts gracefully
Add test cases to cover the same.
**Why**:
Fix #145 
**How**:
Add `|| {}` , to prevent destructuring on `undefined`.
=> Fix scriptname

src/bin-utils/get-script-by-prefix.js, src/bin-utils/get-script-by-prefix.test.js
**What**:
This commit adds a util get-sript-by-prefix.js to bin/utils which takes in a config and a prefix
string as arguments and returns a script if it finds a match, or returns null
**Why**:
This util will help with the issue being fixed in #146 
**How**:
Added a util 'get-string-by-prefix.js' which takes in a config and prefix as arguments and returns a script object if found. Otherwise it returns null.
The script object has the following structure 
`{
name,
description,
script
}`
=> feat: Add util to get a string based on prefix from a config

src/bin-utils/initialize/__tests__/__snapshots__/stringify-object.js.snap, src/bin-utils/initialize/__tests__/fixtures/_package-core-scripts.json, src/bin-utils/initialize/__tests__/fixtures/_package-scripts.js, src/bin-utils/initialize/__tests__/fixtures/_package-scripts.yml, src/bin-utils/initialize/__tests__/fixtures/_package.json, src/bin-utils/initialize/__tests__/index.js, src/bin-utils/initialize/__tests__/stringify-object.js, src/bin-utils/initialize/index.js, src/bin-utils/initialize/stringify-object.js
**What**: Leave npm lifecycle scripts and other core scripts untouched, convert `npm run` commansd to `nps`.
**Why**: To make migrating from npm to nps easier
**How**: 
* Added method which selects core scripts from package.json
* Moved stringify object method to separate module
* Added converting `npm run` scripts to `nps`
**Checklist**:
Hi @kentcdodds . My work is still in progress, tests will be added soon, but first want to make sure that my changes are suitable and also becasue at this point it is easier to revert some changes 😄
=> `init` should not move certain scripts #97

package.json, src/__tests__/get-scripts-from-config.js, src/__tests__/index.js, src/bin-utils/__tests__/index.js, src/bin-utils/initialize/__tests__/index.js
**What**: Use `jest.fn` instead of `sinon.spy`, remove `sinon` dependency
**Why**: `jest` already provides the functionality necessary for testing mock functions. So no need to have `sinon` as a dependency.
**How**: Refactored the tests to use `jest.fn`
**Checklist**:
This was discussed in https://github.com/kentcdodds/nps/pull/161#issuecomment-325157877.
=> test: Use jest mock instead of sinon spy

package.json, src/bin-utils/__tests__/fixtures/fake-config.yml, src/bin-utils/__tests__/index.js, src/bin-utils/index.js, src/bin-utils/parser.js, test/jest.src.config.js
**What**:
All `nps` commands would fail given the following conditions were true:
* User was using a `package-scripts.yml` instead of a `package-scripts.js`
* User didn't pass any options to `nps`
closes #170
**Why**:
Current implementation makes it impossible to call `nps` normally without a minor workaround of some sort.
e.g.
```yml
scripts:
echo: echo "this is a test"
config: {}
```
**How**:
`yml` configurations now go through the same post-process as `js` configurations.
**Checklist**:
=> fix: default config values for yml files

src/bin-utils/initialize/index.js, src/bin-utils/parser.js
**What**:
If a user runs `nps init` in an empty directory with no existing `package.json` the command fails with a non-user friendly error.
**How**:
If this "error" is encountered print a friendly error and exit.
**Comments**:
Instead of exiting out `nps init` could continue without any package.json scripts and use the local directory as the package-scripts.js path.
=> fix: print error on init when cannot find a package.json

src/bin-utils/__tests__/parser.js, src/bin-utils/initialize/index.js, src/bin-utils/parser.js
Sorry for the bad PR, this fixes the bug I introduced and adds a test.  Still not getting 100% coverage, unfortunately.
=> Fixes a bug in PR#181 and adds a test.

src/bin-utils/initialize/__tests__/index.js, src/bin-utils/initialize/index.js
**What**:
The `nps init --type yml` command is not working as expected.
**How**:
Change code to check for the same string as accepted by the parser.
=> fix: fix nps init with config yml

package.json
The version numbers had diverged from the releases on git.
Additionally, some npmjs.com config tweaks for the issue with the lack of executable.
Closes: #213
=> chore: 🤖 Sync version numbers on npm and git
